# Generated by Django 4.2.4 on 2023-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
