# Generated by Django 4.2 on 2023-08-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookdetail_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id', 'age']},
        ),
    ]
